name: Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches: ["master"]

jobs:
  build:
    # Ensure test job passes before pushing image.

    name: Publish binaries
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get current date
        id: date
        run: | 
          echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"
      - name: Build Debian Package
        id: build_package
        run: |
          ls
          pwd
          echo ${{steps.date.outputs.date}}
          mkdir src/DEBIAN
          touch src/DEBIAN/control
          touch src/DEBIAN/md5sums
          touch src/DEBIAN/postinst
          
          echo"""Package: diyorki
          Version: ${{steps.date.outputs.date}}
          Installed-Size: echo $(du -s src/ | cut -f 1)
          Maintainer: Duygu Ölmez <xxx@yyy.com>
          Date : $(date)
          Depends: python3-scp, python3-paramiko
          Architecture: amd64
          Description: Valf
            Uzaktan SSH bağlantısı ve dosya transferi aracı.
          """ > src/DEBIAN/control
        
          find ./src -type f ! -regex '.*?DEBIAN.*' -exec md5sum {} \; > src/DEBIAN/md5sums
          echo """"chmod +x /usr/local/bin/main.py
          chmod +x /usr/local/bin/ssh_file_transfer.py
          chmod +x /usr/local/bin/file_transfer.py""" > src/DEBIAN/postinst
          chmod +x src/DEBIAN/postinst

          mv src valf-${{steps.date.outputs.date}}
          dpkg-deb -Zgzip --build valf-${{steps.date.outputs.date}}

          ls -la  
        
        
        
        
        
        
        
        

          
